name: Generate Pac-Man

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: TruCoded

      - name: Deploy Pac-Man
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pacman-output
          publish_dir: ./dist
